### ISSUE TITLE
Upgrade results in 'payment_label' KeyError

### ISSUE THREAD

**Issue by ezvirtual** [bluedynamics/bda.plone.orders#14]
Hi,
I'm not sure if the upgrade step is working as it should, or if I missed something. I ran the upgrade steps on bda.plone.shop then bda.plone.orders - I only see fix_shipping_attrs log messages and then when trying to view an old order on @@orders I get KeyError: 'payment_label', 

Full Traceback:
http://pastie.org/9121768

Any ideas?

Cheers.

**Comment by rnixx** [comment]
This issue is 2 years old and has no action for a long time. I close this. Please re-open if it's still an issue
