### ISSUE TITLE
Problem adding birthdate to registration form

### ISSUE THREAD

**Issue by marfago** [bluedynamics/bda.plone.orders#21]
Hi,

I am trying to add some extra fields to the registration form in order to see them in the order record.
In particular one of them is the customer birthdate (not mandatory). Following the same approach as for other fields, I added a datetime filed in personal_data.yaml like this:
```
- birthdate:
    factory: "#field:datetime"
```

I see that the corresponding html is:

```
<div id="field-checkout-personal_data-birthdate" class="field">
   <label class="formQuestion">Birthdate<span class="formHelp"></span></label>
   <div id="display-checkout-personal_data-birthdate" class="display-datetime">21/02/2016</div
</div>
```

Using a text field instead, like this 
```
- birthdate:
    factory: "#field:datetime"
```

produces

```
<div id="field-checkout-personal_data-firstname" class="field">
   <label class="formQuestion">First Name<span class="formHelp"></span></label>
   <div id="display-checkout-personal_data-firstname" class="display-text">alex</div>
   <input type="hidden" value="alex" required="required" name="checkout.personal_data.firstname" id="input-checkout-personal_data-firstname" class="required text" originalvalue="alex">
</div>
```

Basically the difference is with the missing hidden input text in the former case, causing  the birthdate not to be added to the order form.

Am I missing anything here? Could you suggest the best approach in your opinion to add a persisted date/time field to the order?
Thank you in advance.

**Comment by rnixx** [comment]
You need to set ``display_proxy`` on the datetime widget in order to get the hidden input rendered along with the displayed value. This issue belongs to https://github.com/bluedynamics/bda.plone.checkout
