### ISSUE TITLE
Maximum recursion depth exceeded when clicking on envelope in backend orders

### ISSUE THREAD

**Issue by marfago** [bluedynamics/bda.plone.orders#26]
When clicking on the envelope on backend order table in order to send an email to the customer I get this error:  

File "/usr/local/Plone-Prod/devsrc/bda.plone.orders/src/bda/plone/orders/browser/notify_customers.py", line 44, in _find_parent
    return _find_parent(aq_parent(context))
RuntimeError: maximum recursion depth exceeded

**Comment by rnixx** [comment]
https://github.com/bluedynamics/bda.plone.orders/blob/master/src/bda/plone/orders/browser/notify_customers.py#L41

either ISite is not provided properly or acquisition context need to be unwrapped with aq_inner in _find_parent.

@thet may you fix this please?

**Comment by thet** [comment]
Need more context on how to reproduce - didn't get this error myself. However, I'm in vacation until 17th August. Can look at this on my return.

**Comment by marfago** [comment]
Any updates on this issue?

**Comment by marfago** [comment]
OK. I think I've found the problem. It works for any context, except when the context is an ISite instance, since the first call is

**Comment by rnixx** [comment]
Thank you for investigation. https://github.com/bluedynamics/bda.plone.orders/commit/aa6c4fcf43a54bebe6b592f9d8a07785f65b470f should fix. Can you try and close the issue please?

**Comment by marfago** [comment]
It works. Thanks.
