### ISSUE TITLE
Sorting the backend table fails

### ISSUE THREAD

**Issue by marfago** [bluedynamics/bda.plone.orders#27]
When sorting the backend table for some attributes (email, state and salaried) it fails with an error:

2015-07-31T11:13:40 ERROR Zope.SiteErrorLog 1438334020.950.670333757341 http://plone/@@ordersdata
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bda.plone.orders.browser.views, line 510, in __call__
  Module bda.plone.orders.browser.views, line 236, in __call__
  Module bda.plone.orders.browser.views, line 583, in query
  Module souper.soup, line 107, in lazy
  Module repoze.catalog.catalog, line 153, in query
  Module repoze.catalog.catalog, line 135, in sort_result
  Module UserDict, line 23, in __getitem__
KeyError: 'state'

**Comment by marfago** [comment]
I'm trying to investigate this issue. Can anyone point me out to a possible starting point?
Thank you in advance.

**Comment by rnixx** [comment]
IIRC, state attribute moved from order record to booking records when vendor feature was implemented. the easiest fix would be to disable sorting for order state. If you like to fix sorting for state you need to add state attribute to order record again and store computed order state on it. But i am not sure right now whether computed order state can differ for different users.

**Comment by marfago** [comment]
Yes, We've found out. We managed to duplicate the state and salaried fields for order , adding the two to BookingData as well. It seems to be working fine for now.

**Comment by rnixx** [comment]
uh, be careful with state on bookings https://github.com/bluedynamics/bda.plone.orders/commit/8249c7ec23fc212d10bd6f541062d9922c646dbe

**Comment by rnixx** [comment]
but you can put your changes to a pull request so we can discuss them

**Comment by marfago** [comment]
Here it comes https://github.com/bluedynamics/bda.plone.orders/pull/30 .

**Comment by rnixx** [comment]
Fixed via #33
