### ISSUE TITLE
Not including reserved items in ``OrderData`` payment information (net, vat) results in items unexpectedly not being paid for

### ISSUE THREAD

**Issue by ezvirtual** [bluedynamics/bda.plone.orders#45]
Can we please talk about this change from #39: 
```
def is_billable_booking(booking):
    """Return True, if booking is billable and should be included in order
    summary calculations.
    To be used in Pythons filter function::
        filter(is_billable_booking, bookings)"""
    
    return booking.attrs['state'] not in (
        ifaces.STATE_RESERVED, ifaces.STATE_CANCELLED
    )

...
   def net(self):
....
        for booking in filter(is_billable_booking, self.bookings):
```

This is a functionality breaking change that I think could do with some discussion. Up until this point, items that have reserved stock levels set have been priced and charged as per usual (unless one selects the option to "Skip payment if order contains back-orders" in the Payment control panel). 

Now the usual pricing is displayed in the cart & checkout right up until the actual payment where it isn't included. 

I think that for this approach to make sense, there needs to be a way for people to then easily pay for the reserved items and there should be a control panel option to toggle this behaviour. As it is it just seems to break expected behaviour by 'silently' not charging customers for items that it looks like they will be paying for.

I'm not sure if I'm missing something or if we've been using reserved as a 'back-order' type functionality in a different way from others?

Cheers

**Comment by rnixx** [comment]
Hi

sorry for the late reply. Yes this change is problematic. It was made for the usecase when indeed an overbooking represents an item which is no longer available except explicitly made available again - thus the term reservation (theater card, and similar). The default behavior should be that reserved items are always charged, with a control panel flag causing the recent behavior.

**Comment by rnixx** [comment]
After some more thinking about this issue I think we should add a flag ``charge_if_backorder`` to ``IStockBehavior``, so we have control per buyable item, and a control panel setting with the default of this value for all buyables.

@thet @jensens @agitator @ezvirtual

**Comment by rnixx** [comment]
Fixed for now via https://github.com/bluedynamics/bda.plone.orders/commit/a5d2fbcb412ab97c74e6c9a9d6f8a8c2de394683

@thet Please don't forget to update ticketshop next time you need to touch it, see commit above.

@ezvirtual @jensens @agitator @thet Partly billable bookings within one order need more love to happen reliably. More details can be found in PR https://github.com/bluedynamics/bda.plone.orders/pull/51
